import type { Translations } from "@eigenpal/docx-js-editor"

export const DOCX_EDITOR_PT_BR = {
  _lang: "pt-BR",
  common: {
    cancel: "Cancelar",
    insert: "Inserir",
    apply: "Aplicar",
    close: "Fechar",
    delete: "Excluir",
    update: "Atualizar",
    save: "Salvar",
    retry: "Tentar novamente",
    send: "Enviar",
    edit: "Editar",
    comment: "Comentário",
    reply: "Responder",
    accept: "Aceitar",
    reject: "Rejeitar",
    dismiss: "Dispensar",
    change: "Alterar",
    px: "px",
    closeDialog: "Fechar janela",
  },
  toolbar: {
    ariaLabel: "Barra de formatação",
    file: "Arquivo",
    format: "Formatar",
    insert: "Inserir",
    print: "Imprimir",
    printShortcut: "Ctrl+P",
    pageSetup: "Configurar página",
    leftToRight: "Texto da esquerda para a direita",
    rightToLeft: "Texto da direita para a esquerda",
    image: "Imagem",
    table: "Tabela",
    pageBreak: "Quebra de página",
    tableOfContents: "Sumário",
    symbol: "Símbolo",
    help: "Ajuda",
    reportIssue: "Reportar problema",
  },
  formattingBar: {
    groups: {
      history: "Histórico",
      zoom: "Zoom",
      styles: "Estilos",
      font: "Fonte",
      textFormatting: "Formatação de texto",
      script: "Subscrito e sobrescrito",
      alignment: "Alinhamento",
      listFormatting: "Listas",
      image: "Imagem",
      table: "Tabela",
    },
    undo: "Desfazer",
    undoShortcut: "Desfazer (Ctrl+Z)",
    redo: "Refazer",
    redoShortcut: "Refazer (Ctrl+Y)",
    bold: "Negrito",
    boldShortcut: "Negrito (Ctrl+B)",
    italic: "Itálico",
    italicShortcut: "Itálico (Ctrl+I)",
    underline: "Sublinhado",
    underlineShortcut: "Sublinhado (Ctrl+U)",
    strikethrough: "Tachado",
    fontColor: "Cor da fonte",
    highlightColor: "Cor de realce do texto",
    insertLink: "Inserir link",
    insertLinkShortcut: "Inserir link (Ctrl+K)",
    superscript: "Sobrescrito",
    superscriptShortcut: "Sobrescrito (Ctrl+Shift+=)",
    subscript: "Subscrito",
    subscriptShortcut: "Subscrito (Ctrl+=)",
    imageProperties: "Propriedades da imagem",
    imagePropertiesShortcut: "Propriedades da imagem (texto alternativo, borda)...",
    clearFormatting: "Limpar formatação",
  },
  alignment: {
    alignLeft: "Alinhar à esquerda",
    alignLeftShortcut: "Ctrl+L",
    center: "Centralizar",
    centerShortcut: "Ctrl+E",
    alignRight: "Alinhar à direita",
    alignRightShortcut: "Ctrl+R",
    justify: "Justificar",
    justifyShortcut: "Ctrl+J",
  },
  lists: {
    ariaLabel: "Formatação de lista",
    typeAriaLabel: "Tipo de lista",
    indentationAriaLabel: "Recuo da lista",
    bulletList: "Lista com marcadores",
    numberedList: "Lista numerada",
    decreaseIndent: "Diminuir recuo",
    increaseIndent: "Aumentar recuo",
  },
  lineSpacing: {
    single: "Simples",
    double: "Duplo",
    lineSpacingTitle: "Espaçamento: {label}",
    paragraphSpacing: "Espaçamento do parágrafo",
  },
  styles: {
    selectAriaLabel: "Selecionar estilo do parágrafo",
    normalText: "Texto normal",
    title: "Título",
    subtitle: "Subtítulo",
    heading1: "Título 1",
    heading2: "Título 2",
    heading3: "Título 3",
  },
  font: {
    selectAriaLabel: "Selecionar família da fonte",
    sansSerif: "Sem serifa",
    serif: "Serifada",
    monospace: "Monoespaçada",
  },
  fontSize: {
    decrease: "Diminuir tamanho da fonte",
    increase: "Aumentar tamanho da fonte",
    label: "Tamanho da fonte",
    listLabel: "Tamanhos de fonte",
  },
  zoom: {
    ariaLabel: "Zoom: {label}",
  },
  colorPicker: {
    ariaLabel: "Seletor de cor: {type}",
    highlightColors: "Cores de realce",
    customColor: "Cor personalizada",
    noColor: "Sem cor",
    automatic: "Automático",
    themeColors: "Cores do tema",
    standardColors: "Cores padrão",
    colors: {
      black: "Preto",
      darkRed: "Vermelho escuro",
      red: "Vermelho",
      orange: "Laranja",
      yellow: "Amarelo",
      darkYellow: "Amarelo escuro",
      green: "Verde",
      darkGreen: "Verde escuro",
      teal: "Azul-petróleo",
      darkTeal: "Azul-petróleo escuro",
      blue: "Azul",
      darkBlue: "Azul escuro",
      purple: "Roxo",
      darkPurple: "Roxo escuro",
      brown: "Marrom",
      grey50: "Cinza 50%",
      grey25: "Cinza 25%",
      grey10: "Cinza 10%",
      white: "Branco",
      lightRed: "Vermelho claro",
      lightOrange: "Laranja claro",
      lightYellow: "Amarelo claro",
      lightGreen: "Verde claro",
      lightBlue: "Azul claro",
      lightPurple: "Roxo claro",
      pink: "Rosa",
      rose: "Rosé",
      gold: "Dourado",
      aqua: "Água",
      lavender: "Lavanda",
      silver: "Prata",
      darkOrange: "Laranja escuro",
      darkGray: "Cinza escuro",
      gray: "Cinza",
      cyan: "Ciano",
      magenta: "Magenta",
      paleGreen: "Verde pálido",
      lightCyan: "Ciano claro",
      skyBlue: "Azul céu",
      lightBlue2: "Azul claro 2",
      lightMagenta: "Magenta claro",
      brightGreen: "Verde brilhante",
      violet: "Violeta",
    },
  },
  dialogs: {
    findReplace: {
      titleFind: "Localizar",
      titleFindReplace: "Localizar e substituir",
      findLabel: "Localizar:",
      findPlaceholder: "Digite o texto para localizar...",
      findAriaLabel: "Localizar texto",
      findPrevious: "Localizar anterior",
      findPreviousTitle: "Localizar anterior (Shift+Enter)",
      findNext: "Localizar próximo",
      findNextTitle: "Localizar próximo (Enter)",
      matchCount: "{current} de {total} ocorrências",
      noResults: "Nenhum resultado encontrado",
      replaceLabel: "Substituir:",
      replacePlaceholder: "Digite o texto substituto...",
      replaceAriaLabel: "Substituir texto",
      replaceButton: "Substituir",
      replaceCurrentTitle: "Substituir ocorrência atual",
      replaceAllButton: "Substituir tudo",
      replaceAllTitle: "Substituir todas as ocorrências",
      matchCase: "Diferenciar maiúsculas/minúsculas",
      wholeWords: "Palavras inteiras",
      toggleReplace: "+ Substituir",
    },
    hyperlink: {
      titleEdit: "Editar hiperlink",
      titleInsert: "Inserir hiperlink",
      tabWebAddress: "Endereço web",
      tabBookmark: "Marcador",
      urlLabel: "URL",
      urlPlaceholder: "https://exemplo.com",
      urlHint: "Informe um endereço web, e-mail (mailto:) ou telefone (tel:)",
      bookmarkLabel: "Marcador",
      bookmarkPlaceholder: "Selecione um marcador...",
      displayTextLabel: "Texto exibido",
      displayTextPlaceholder: "Texto para exibir (opcional)",
      displayTextHint: "Deixe vazio para usar o texto selecionado",
      tooltipLabel: "Tooltip (opcional)",
      tooltipPlaceholder: "Texto exibido ao passar o mouse",
      removeLink: "Remover link",
      invalidUrl: "Informe uma URL válida",
      urlRequired: "A URL é obrigatória",
    },
    insertTable: {
      title: "Inserir tabela",
      hoverToSelect: "Passe o mouse para selecionar o tamanho",
      tableSize: "Tabela {cols} x {rows}",
      orSpecifySize: "ou especifique o tamanho",
      rowsLabel: "Linhas:",
      columnsLabel: "Colunas:",
      insertButton: "Inserir tabela",
      sizeSelector: "Seletor de tamanho da tabela",
    },
    splitCell: {
      title: "Dividir célula",
      description: "Defina quantas linhas e colunas serão criadas a partir da célula selecionada.",
      rowsLabel: "Linhas:",
      columnsLabel: "Colunas:",
      currentMinimum: "Mínimo pelo intervalo atual: {rows} linha(s) x {cols} coluna(s)",
      minValue: "Use pelo menos {rows} linha(s) e {cols} coluna(s).",
      notOneByOne: "Escolha pelo menos duas células resultantes.",
    },
    insertImage: {
      title: "Inserir imagem",
      uploadAriaLabel: "Clique ou arraste para enviar uma imagem",
      uploadText: "Clique para selecionar ou arraste e solte uma imagem",
      uploadSubtext: "PNG, JPG, GIF até 10MB",
      dimensions: "Dimensões",
      widthLabel: "Largura:",
      heightLabel: "Altura:",
      aspectRatioLocked: "Proporção travada",
      aspectRatioUnlocked: "Proporção destravada",
      altTextLabel: "Texto alternativo (opcional)",
      altTextPlaceholder: "Descreva a imagem para acessibilidade",
      insertButton: "Inserir imagem",
      invalidFile: "Selecione um arquivo de imagem válido",
      fileTooLarge: "Arquivo de imagem muito grande (máx. 10MB)",
      readFailed: "Não foi possível ler a imagem",
      loadFailed: "Não foi possível carregar a imagem",
      preview: "Prévia",
    },
    insertSymbol: {
      title: "Inserir símbolo",
      searchPlaceholder: "Buscar símbolos (caractere ou Unicode)...",
      noResults: "Nenhum símbolo encontrado para \"{query}\"",
      decimal: "Decimal: {value}",
      categories: {
        common: "Comuns",
        arrows: "Setas",
        math: "Matemática",
        greek: "Grego",
        shapes: "Formas",
        punctuation: "Pontuação",
        currency: "Moedas",
        music: "Música",
        emoji: "Emoji",
      },
    },
    imageProperties: {
      title: "Propriedades da imagem",
      altText: "Texto alternativo",
      altTextPlaceholder: "Descreva esta imagem para acessibilidade...",
      border: "Borda",
      width: "Largura",
      style: "Estilo",
      color: "Cor",
      preview: "Prévia",
      borderStyles: {
        solid: "Sólida",
        dashed: "Tracejada",
        dotted: "Pontilhada",
        double: "Dupla",
        groove: "Entalhada",
        ridge: "Relevo",
        inset: "Baixo relevo",
        outset: "Alto relevo",
      },
    },
    imagePosition: {
      title: "Posição da imagem",
      horizontal: "Horizontal",
      vertical: "Vertical",
      position: "Posição",
      alignment: "Alinhamento",
      offset: "Deslocamento",
      offsetPx: "Deslocamento (px)",
      align: "Alinhar",
      relativeTo: "Relativo a",
      alignOptions: {
        left: "Esquerda",
        center: "Centro",
        right: "Direita",
        top: "Topo",
        bottom: "Base",
      },
      relativeOptions: {
        page: "Página",
        column: "Coluna",
        margin: "Margem",
        character: "Caractere",
        paragraph: "Parágrafo",
        line: "Linha",
      },
    },
    pageSetup: {
      title: "Configurar página",
      pageSize: "TAMANHO DA PÁGINA",
      sizeLabel: "Tamanho",
      custom: "Personalizado",
      orientation: "Orientação",
      portrait: "Retrato",
      landscape: "Paisagem",
      margins: "MARGENS",
      top: "Superior",
      bottom: "Inferior",
      left: "Esquerda",
      right: "Direita",
    },
    tableProperties: {
      title: "Propriedades da tabela",
      widthType: "Tipo de largura",
      widthLabel: "Largura",
      alignmentLabel: "Alinhamento",
      widthTypes: {
        auto: "Automática",
        fixed: "Fixa (twips)",
        percentage: "Porcentagem",
      },
      alignOptions: {
        left: "Esquerda",
        center: "Centro",
        right: "Direita",
      },
    },
    pasteSpecial: {
      title: "Colagem especial",
      keepFormatting: "Manter formatação original",
      keepFormattingDescription: "Colar com a formatação original",
      plainText: "Colar como texto sem formatação",
      plainTextDescription: "Colar sem nenhuma formatação",
      readingClipboard: "Lendo área de transferência...",
      preview: "Prévia:",
      noContent: "Nenhum conteúdo disponível para colar",
      clipboardError: "Não foi possível ler a área de transferência. Use Ctrl+V para colar.",
    },
    keyboardShortcuts: {
      ariaLabel: "Atalhos de teclado",
      searchPlaceholder: "Buscar atalhos...",
      categories: {
        editing: "Edição",
        formatting: "Formatação",
        navigation: "Navegação",
        clipboard: "Área de transferência",
        selection: "Seleção",
        view: "Visualização",
        file: "Arquivo",
        other: "Outros",
      },
      noResults: "Nenhum atalho encontrado para \"{query}\"",
      pressEscToClose: "Pressione {key} para fechar",
      or: "ou",
    },
  },
  comments: {
    resolved: "Resolvido",
    resolve: "Resolver",
    reopen: "Reabrir",
    moreOptions: "Mais opções",
    unknown: "Desconhecido",
    addComment: "Adicionar comentário...",
    replyPlaceholder: "Responda ou adicione pessoas com @",
    replyCount: "{count, plural, one {# resposta} other {# respostas}}",
  },
  trackedChanges: {
    unknown: "Desconhecido",
    replaced: "Substituído",
    with: "por",
    added: "Adicionado",
    deleted: "Excluído",
  },
  contextMenu: {
    ariaLabel: "Menu de ações de IA",
    textMenuAriaLabel: "Menu de edição de texto",
    customPromptPlaceholder: "Digite um prompt personalizado...",
    cut: "Recortar",
    copy: "Copiar",
    paste: "Colar",
    pastePlainText: "Colar como texto sem formatação",
    delete: "Excluir",
    selectAll: "Selecionar tudo",
    selected: "Selecionado:",
    aiActions: {
      askAi: "Perguntar à IA",
      rewrite: "Reescrever",
      expand: "Expandir",
      summarize: "Resumir",
      translate: "Traduzir",
      explain: "Explicar",
      fixGrammar: "Corrigir gramática",
      makeFormal: "Tornar formal",
      makeCasual: "Tornar informal",
      custom: "Personalizado",
    },
  },
  documentOutline: {
    ariaLabel: "Estrutura do documento",
    closeAriaLabel: "Fechar estrutura",
    closeTitle: "Fechar estrutura",
    title: "Estrutura",
    noHeadings: "Nenhum título encontrado. Adicione títulos ao documento para vê-los aqui.",
  },
  sidebar: {
    ariaLabel: "Barra lateral de anotações",
  },
  titleBar: {
    untitled: "Sem título",
    documentNameAriaLabel: "Nome do documento",
    menuBarAriaLabel: "Barra de menu",
  },
  errors: {
    loadingDocument: "Carregando documento...",
    noDocumentLoaded: "Nenhum documento carregado",
    failedToLoad: "Falha ao carregar documento",
    unableToParse: "Não foi possível interpretar o documento",
    somethingWentWrong: "Algo deu errado",
    errorDescription: "Ocorreu um erro ao renderizar este componente. Tente novamente ou contate o suporte.",
    errorLabel: "Erro:",
    componentStack: "Pilha do componente:",
    tryAgain: "Tentar novamente",
    showDetails: "Mostrar detalhes",
    hideDetails: "Ocultar detalhes",
    unsavedChanges: "Você tem alterações não salvas. Tem certeza que deseja sair?",
  },
  table: {
    insertRowAbove: "Inserir linha acima",
    insertRowBelow: "Inserir linha abaixo",
    insertColumnLeft: "Inserir coluna à esquerda",
    insertColumnRight: "Inserir coluna à direita",
    deleteRow: "Excluir linha",
    deleteColumn: "Excluir coluna",
    deleteTable: "Excluir tabela",
    mergeCells: "Mesclar células",
    splitCell: "Dividir célula",
    editingTools: "Ferramentas de edição da tabela",
    label: "Tabela:",
    cellFillColor: "Cor de fundo da célula",
    borderColor: "Cor da borda",
    borderWidth: "Largura da borda",
    unknownAction: "Ação desconhecida",
    borders: {
      all: "Todas as bordas",
      outside: "Bordas externas",
      inside: "Bordas internas",
      none: "Sem bordas",
      remove: "Remover bordas",
      top: "Borda superior",
      bottom: "Borda inferior",
      left: "Borda esquerda",
      right: "Borda direita",
      styleAriaLabel: "Estilo da borda",
      tooltip: "Bordas",
    },
    moreOptions: "Mais opções de tabela",
    styles: {
      title: "Estilos de tabela",
      label: "Estilos",
      normalTable: "Tabela normal",
      tableGrid: "Tabela com grade",
    },
  },
  tableAdvanced: {
    verticalAlignment: "Alinhamento vertical",
    top: "Topo",
    middle: "Meio",
    bottom: "Base",
    cellMargins: "Margens da célula",
    textDirection: "Direção do texto",
    toggleNoWrap: "Alternar sem quebra de linha",
    rowHeight: "Altura da linha",
    rule: "Regra",
    height: "Altura",
    toggleHeaderRow: "Alternar linha de cabeçalho",
    distributeColumns: "Distribuir colunas uniformemente",
    autoFit: "Ajustar ao conteúdo",
    tableProperties: "Propriedades da tabela...",
    tableAlignment: "Alinhamento da tabela",
    alignTableLeft: "Alinhar tabela à esquerda",
    alignTableCenter: "Centralizar tabela",
    alignTableRight: "Alinhar tabela à direita",
    tableOptionsMenu: "Menu de opções da tabela",
    tableOptions: "Opções da tabela",
  },
  imageTransform: {
    tooltip: "Transformar",
    rotateClockwise: "Girar no sentido horário",
    rotateCounterClockwise: "Girar no sentido anti-horário",
    flipHorizontal: "Espelhar horizontalmente",
    flipVertical: "Espelhar verticalmente",
  },
  imageWrap: {
    inline: "Em linha com o texto",
    floatLeft: "Flutuar à esquerda (texto à direita)",
    floatRight: "Flutuar à direita (texto à esquerda)",
    topAndBottom: "Acima e abaixo",
    behindText: "Atrás do texto",
    inFrontOfText: "Na frente do texto",
    tooltipPrefix: "Quebra de texto: {label}",
  },
  responsePreview: {
    loading: "{action}...",
    result: "Resultado de {action}",
    closeEsc: "Fechar (Esc)",
    editPrompt: "Edite o resultado antes de aceitar:",
    changes: "Alterações:",
    original: "Original:",
    new: "Novo:",
    cancelEdit: "Cancelar edição",
  },
  commentMarkers: {
    resolvedComment: "Comentário resolvido",
    comment: "Comentário",
  },
  editor: {
    toggleCommentsSidebar: "Alternar barra lateral de comentários",
    showDocumentOutline: "Mostrar estrutura do documento",
    editing: "Editando",
    editingDescription: "Editar documento diretamente",
    suggesting: "Sugerindo",
    suggestingDescription: "Edições viram sugestões",
    viewing: "Visualizando",
    viewingDescription: "Somente leitura, sem edições",
    failedToParse: "Falha ao interpretar o documento",
    linkRemoved: "Link removido",
    linkCopied: "Link copiado para a área de transferência",
    failedToSave: "Falha ao salvar documento",
  },
  hyperlinkPopup: {
    displayTextPlaceholder: "Texto exibido",
    urlPlaceholder: "https://exemplo.com",
    copyLink: "Copiar link",
    editLink: "Editar link",
    removeLink: "Remover link",
  },
  headerFooter: {
    header: "Cabeçalho",
    footer: "Rodapé",
    options: "Opções",
    insertPageNumber: "Inserir número da página atual",
    insertTotalPages: "Inserir total de páginas",
    remove: "Remover {label}",
    closeEditing: "Fechar edição de {label}",
  },
  image: {
    placeholder: "Espaço reservado de imagem",
    placeholderText: "[Imagem]",
    editableAriaLabel: "Imagem editável",
  },
  ruler: {
    horizontal: "Régua horizontal",
    vertical: "Régua vertical",
    firstLineIndent: "Recuo da primeira linha",
    leftIndent: "Recuo esquerdo",
    rightIndent: "Recuo direito",
    topMargin: "Margem superior",
    bottomMargin: "Margem inferior",
  },
  print: {
    label: "Imprimir",
    allPages: "Todas ({totalPages} páginas)",
    singlePage: "Página {start}",
    pageRange: "Páginas {start}-{end}",
  },
  unsaved: {
    unsaved: "Não salvo",
    saved: "Salvo",
    unsavedTitle: "O documento tem alterações não salvas",
    savedTitle: "Todas as alterações foram salvas",
    unsavedAriaLabel: "Alterações não salvas",
    savedAriaLabel: "Todas as alterações foram salvas",
  },
  loading: {
    label: "Carregando",
  },
} satisfies Translations
