import type { Notification } from "@/lib/types"

// Temporário: notificações ainda não têm backend dedicado.
export const notifications: Notification[] = [
  {
    id: "notif1",
    type: "new_schedule",
    title: "Novo Agendamento",
    message: "Serviço de Desentupimento agendado para Condomínio Eduardo Prado em 15/03/2026",
    channels: ["system", "whatsapp"],
    recipientTeamIds: ["team1"],
    relatedScheduleId: "sched1",
    relatedClientId: "client1",
    isRead: false,
    sentAt: new Date("2026-02-25"),
    createdAt: new Date("2026-02-25"),
  },
  {
    id: "notif2",
    type: "emergency",
    title: "Serviço Emergencial",
    message: "Entupimento emergencial no Edifício Comercial Centro - Atendimento imediato necessário",
    channels: ["system", "whatsapp"],
    recipientTeamIds: ["team1"],
    relatedScheduleId: "sched4",
    relatedClientId: "client3",
    isRead: true,
    sentAt: new Date("2026-03-09"),
    readAt: new Date("2026-03-09"),
    createdAt: new Date("2026-03-09"),
  },
  {
    id: "notif3",
    type: "payment_overdue",
    title: "Parcela Vencida",
    message: "Parcela 3 do contrato DEP-2026-003 está vencida desde 15/03/2026",
    channels: ["system"],
    relatedContractId: "contract3",
    relatedClientId: "client3",
    isRead: false,
    sentAt: new Date("2026-03-16"),
    createdAt: new Date("2026-03-16"),
  },
  {
    id: "notif4",
    type: "daily_services",
    title: "Serviços do Dia",
    message: "Você tem 2 serviços agendados para hoje",
    channels: ["system", "whatsapp"],
    recipientTeamIds: ["team1"],
    isRead: true,
    sentAt: new Date("2026-03-09"),
    readAt: new Date("2026-03-09"),
    createdAt: new Date("2026-03-09"),
  },
]
